version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php-fpm

  php-fpm:
    image: php:8.2-fpm
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: p@ssw0rd
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MARIADB_ROOT_PASSWORD: p@ssw0rd
    ports:
      - "8001:80"
    depends_on:
      - db